# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import digitizer_correlation_grpc_pb2 as digitizer__correlation__grpc__pb2


class DigitizerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.measure_correlation_matrix = channel.unary_unary(
        '/Digitizer/measure_correlation_matrix',
        request_serializer=digitizer__correlation__grpc__pb2.DigParams.SerializeToString,
        response_deserializer=digitizer__correlation__grpc__pb2.CorrelationMatrix.FromString,
        )


class DigitizerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def measure_correlation_matrix(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DigitizerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'measure_correlation_matrix': grpc.unary_unary_rpc_method_handler(
          servicer.measure_correlation_matrix,
          request_deserializer=digitizer__correlation__grpc__pb2.DigParams.FromString,
          response_serializer=digitizer__correlation__grpc__pb2.CorrelationMatrix.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Digitizer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
