# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digitizer_correlation_grpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='digitizer_correlation_grpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n digitizer_correlation_grpc.proto\"\x84\x01\n\tDigParams\x12\x10\n\x08\x63hannels\x18\x01 \x01(\x04\x12\x14\n\x0c\x63h_amplitude\x18\x02 \x01(\x04\x12\x0f\n\x07\x64ur_seg\x18\x03 \x01(\x02\x12\r\n\x05n_seg\x18\x04 \x01(\x04\x12\x1b\n\x13oversampling_factor\x18\x05 \x01(\x04\x12\x12\n\npretrigger\x18\x06 \x01(\x04\";\n\x11\x43orrelationMatrix\x12\x11\n\ttrace_len\x18\x01 \x01(\x05\x12\x13\n\x07samples\x18\x02 \x03(\x02\x42\x02\x10\x01\x32K\n\tDigitizer\x12>\n\x1ameasure_correlation_matrix\x12\n.DigParams\x1a\x12.CorrelationMatrix\"\x00\x62\x06proto3')
)




_DIGPARAMS = _descriptor.Descriptor(
  name='DigParams',
  full_name='DigParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='DigParams.channels', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ch_amplitude', full_name='DigParams.ch_amplitude', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dur_seg', full_name='DigParams.dur_seg', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_seg', full_name='DigParams.n_seg', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oversampling_factor', full_name='DigParams.oversampling_factor', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pretrigger', full_name='DigParams.pretrigger', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=169,
)


_CORRELATIONMATRIX = _descriptor.Descriptor(
  name='CorrelationMatrix',
  full_name='CorrelationMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trace_len', full_name='CorrelationMatrix.trace_len', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='samples', full_name='CorrelationMatrix.samples', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=230,
)

DESCRIPTOR.message_types_by_name['DigParams'] = _DIGPARAMS
DESCRIPTOR.message_types_by_name['CorrelationMatrix'] = _CORRELATIONMATRIX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DigParams = _reflection.GeneratedProtocolMessageType('DigParams', (_message.Message,), dict(
  DESCRIPTOR = _DIGPARAMS,
  __module__ = 'digitizer_correlation_grpc_pb2'
  # @@protoc_insertion_point(class_scope:DigParams)
  ))
_sym_db.RegisterMessage(DigParams)

CorrelationMatrix = _reflection.GeneratedProtocolMessageType('CorrelationMatrix', (_message.Message,), dict(
  DESCRIPTOR = _CORRELATIONMATRIX,
  __module__ = 'digitizer_correlation_grpc_pb2'
  # @@protoc_insertion_point(class_scope:CorrelationMatrix)
  ))
_sym_db.RegisterMessage(CorrelationMatrix)


_CORRELATIONMATRIX.fields_by_name['samples']._options = None

_DIGITIZER = _descriptor.ServiceDescriptor(
  name='Digitizer',
  full_name='Digitizer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=232,
  serialized_end=307,
  methods=[
  _descriptor.MethodDescriptor(
    name='measure_correlation_matrix',
    full_name='Digitizer.measure_correlation_matrix',
    index=0,
    containing_service=None,
    input_type=_DIGPARAMS,
    output_type=_CORRELATIONMATRIX,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIGITIZER)

DESCRIPTOR.services_by_name['Digitizer'] = _DIGITIZER

# @@protoc_insertion_point(module_scope)
